// Generated by https://quicktype.io

// export interface User {
//   num_documento: number;
//   user:          string;
//   email:         string;
// }


export interface User {
  _id:      string;
  email:    string;
  name:     string;
  isActive: boolean;
  roles:    string[];
}
