// Generated by https://quicktype.io

import { Roles } from "./auth-roles.enum";

// export interface User {
//   num_documento: number;
//   user:          string;
//   email:         string;
// }


export interface User {
  _id:       string;
  documento: string;
  email:     string;
  name:      string;
  password:  string;
  isActive:  boolean;
  rol:     Roles;
}

// export enum Roles {
//   admin = "admin",
//   user = "user",
// }
