// Generated by https://quicktype.io

export interface Order {
  id_orden:                 string;
  codigo_de_orden:          string;
  ubicacion:                string;
  cliente:                  string;
  producto:                 string;
  proceso_actual:           string;
  color_elegido:            string;
  cantidad:                 number;
  fecha_de_inicio:          string;
  fecha_estimada_de_salida: string;
  fecha_de_creacion:        string;
}
